[component.questions-table]
datasource = """
read questions.json and save it to <questions>
pick 2 random questions from <questions> and save it to <questions>
"""
id = "questions-table"
type = "html_table"
header.id.label = "ID"
header.id.data = "<question.id>"
header.question.label = "QUESTION"
header.question.data = "<question.body>"
header.style.background = "lightYellow"
header.style.textalign = "left"
style.detail = "background: light yellow, border: 1px blue solid"
cell.hover_on = "change cell.style.font-weight: bold"
cell.hover_off = "change cell.style.font-weight: normal"
cell.click = """
pop up a message: "question details: <question.body> (<row_number>, <column_number>)"
"""
cell.style.background = "wheat"
cell.style.textalign = "center"
row.start_index = 1
