[component.question-popup]
datasource = "<question>"
type = "html div"
style.detail = """
width: 400px
height: 300px
align: center of the screen
background: #27CCF5
visibility: hidden
"""
click = "if outside of this component's boundary,visibility: hidden"
inner_html = "<question.body>"
