[component.questions-list]
type = "html section with paragraphs"
datasource="<question> in <questions> from logic.php.get_random_questions"
paragraph.style.detail = "margin left 10px, margin right 10px"
paragraph.odd.style.background = "light green"
paragraph.even.style.background = "green"
paragraph.hover_on = """
cell.style.font-weight: bold
cell.style.mouse-cursor: hand
"""
paragraph.hover_off = "change cell.style.font-weight: normal"
