[component.questions-list]
type = "html section with paragraphs"
datasource="""
read questions.json and save it to <questions>
pick 4 random questions from <questions> and save it to <questions>
"""
paragraph.style.detail = "margin left 10px, margin right 10px"
paragraph.odd.style.background = "light green"
paragraph.even.style.background = "green"
paragraph.hover_on = """
current_paragraph.style.font-weight: bold
current_paragraph.style.mouse-cursor: spinning ring
"""
paragraph.hover_off = "current_paragraph.style.font-weight: normal"
paragraph.click = """
component.question-popup.style.visibility = "visible"
component.question-popup.datasource = "<question> in <questions>"
"""
