[component.questions-table]
datasource = "read questions.json and save it to <questions>\npick 2 random questions from <questions> and save it to <questions>\n"
type = "html table"
click = "pop up a message: \"question details: <question.body> (<row_number>, <column_number>)\"\n"

[component.questions-list]
type = "html section with paragraphs"
datasource = "read questions.json and save it to <questions>\npick 4 random questions from <questions> and save it to <questions>\n"
hover_on = "current_paragraph.style.font-weight: bold\ncurrent_paragraph.style.mouse-cursor: spinning ring\n"

[component.questions-table.style]
detail = "background: light yellow, border: 3px gold solid"

[component.questions-table.cell]
hover_on = "change cell.style.font-weight: bold"
hover_off = "change cell.style.font-weight: normal"

[component.questions-table.row]
start_index = 1

[component.questions-list.paragraph]
hover_off = "current_paragraph.style.font-weight: normal"

[logic.php.get_random_questions]
details = "read questions.json and save it to <questions>\npick 2 random questions from <questions> and save it to <questions>\nreturn <questions>\n"

[component.questions-table.header.id]
label = "ID"
data = "<question.id>"

[component.questions-table.header.question]
label = "QUESTION"
data = "<question.body>"

[component.questions-table.header.style]
background = "lightYellow"
textalign = "left"

[component.questions-table.cell.style]
background = "wheat"
textalign = "center"

[component.questions-list.paragraph.style]
detail = "margin left 10px, margin right 10px"

[component.questions-list.paragraph.odd.style]
background = "light red"

[component.questions-list.paragraph.even.style]
background = "red"

