[component.questions-list]
type = "html section with paragraphs"
datasource = "read questions.json and save it to <questions>\npick 4 random questions from <questions> and save it to <questions>\neach paragraph maps to <question> in <questions>\n"
hover_on = "current_paragraph.style.font-weight: bold\ncurrent_paragraph.style.mouse-cursor: spinning ring\n"
click = "component.question-popup.style.visibility = \"visible\"\ncomponent.question-popup.datasource = \"<question> in <questions>\"\n"

[component.questions-list.paragraph]
hover_off = "current_paragraph.style.font-weight: normal"

[component.questions-list.paragraph.style]
detail = "margin left 10px, margin right 10px"

[component.questions-list.paragraph.odd.style]
background = "light green"

[component.questions-list.paragraph.even.style]
background = "green"

