@include component.questions-table.toml
@include component.questions-list.toml

[logic.php.get_random_questions]
details = """
read questions.json and save it to <questions>
pick 2 random questions from <questions> and save it to <questions>
return <questions>
"""

@include custom.toml
