[logic.php.get_random_questions]
detail = """
- read questions.json and save it to <questions>
- pick 4 random questions from <questions> and save it to <questions>
"""
return = "<questions>"

[logic.js.show_alert_message]
params.row_number = "<row_number>"
params.column_number = "<column_number>"
details = """
alert a message "you are clicking on row <row_number>, column <column_number>"
"""

[components.questions-table]
id = "questions-table"
type = "html_table"
datasource = "<question> in <questions> from logic.php.get_random_questions"
headers.id.label = "ID"
headers.id.data = "<question.id>"
headers.question.label = "QUESTION"
headers.question.data = "<question.body>"
headers.style.background = "lightYellow"
headers.style.textalign = "left"
style.background = "lightYellow"
style.border = "1px, blue, solid"
cells.onclick = "logic.js.show_alert_message(<row_number>, <column_number>)"
cells.style.background = "wheat"
cells.style.textalign = "right"
rows.start_index = 1

[components.questoins-list]
id = "questions-list"
type = "html_div_with_paragraphs"
datasource = "<question> in <questions> from logic.php.get_random_questions"
paragraph.odd.style.background = "yellow"
paragraph.even.style.background = "light yellow"
