@include component.questions-table.toml

[component.questions-list]
type = "html section with paragraphs"
datasource="get questions from logic.php.get_random_questions"
paragraph.style.detail = "margin left 10px, margin right 10px"
paragraph.odd.style.background = "light green"
paragraph.even.style.background = "green"

[logic.php.get_random_questions]
details = """
read questions.json and save it to <questions>
pick 2 random questions from <questions> and save it to <questions>
return <questions>
"""

[logic.js.show_alert_message]
param.row_number = "<row_number>"
param.column_number = "<column_number>"
param.question = "<question>"
detail = """
pop up a message:"<question.body>"
"""

@include custom.toml
