[logic.php.get_random_questions]
details = """
- read questions.json and save it to <questions>
- pick 4 random questions from <questions> and save it to <questions>
"""
return = "<questions>"

[logic.js.show_alert_message]
params.row_number = "<row_number>"
params.column_number = "<column_number>"
params.question = "<question>"
details = """
alert a message "you clicked on row <row_number>, column <column_number>, question id: <question.id>"
"""

[[components]]
id = "questions-table"
type = "html_table"
datasource = "<question> in <questions> from logic.php.get_random_questions"
headers.id.label = "ID"
headers.id.data = "<question.id>"
headers.question.label = "QUESTION"
headers.question.data = "<question.body>"
headers.style.background = "lightYellow"
headers.style.textalign = "left"
style.background = "lightYellow"
style.border = "1px, blue, solid"
cells.style.details = """
padding: 10px
"""
cells.onclick = "logic.js.show_alert_message(<row_number>, <column_number>, <question>)"
cells.style.background = "wheat"
cells.style.textalign = "right"
rows.start_index = 1

[[components]]
id = "questions-list"
type = "html_div_wrapping_paragraphs"
datasource = "<question> in <questions> from logic.php.get_random_questions"
paragraphs.style.details = """
margin left: 10px; 
margin-right: 10px"
"""
paragraphs.odd.style.background = "yellow"
paragraphs.even.style.background = "light yellow"
